### ISSUE TITLE
Ability to set `?rel=0` to stop related video's showing

### ISSUE THREAD

**Issue by katie-day** [springload/Quicktube.js#9]
Currently when you pause the video, a related video 'carousel' pops up. I would like to discourage users from being distracted or tempted by other videos when they pause the video. 

By adding `?rel=0` by default or as an option would be a useful feature. 

Link to the [youtube docs](https://developers.google.com/youtube/player_parameters#rel) on `rel`

**Comment by katie-day** [comment]
Add `rel=0` into after [line 91](https://github.com/springload/quicktube/blob/f3a38ff639f89b2b37eb31c191b3feded90e888b/src/quicktube.js#L91)

**Comment by liamjohnston** [comment]
@katie-day I guess you can close this as of `3.1.0`?
